### ISSUE TITLE
pyTLDR installation issue  

### ISSUE THREAD

**Issue by AkshayVaghani** [jaijuneja/PyTLDR#3]
akshay@Akshays-MacBook-Pro:/anaconda3/lib/python3.6/site-packages/skipthoughts$ pip install PyTLDR
Collecting PyTLDR
  Using cached https://files.pythonhosted.org/packages/70/09/02ed27061159e5f6d35abad4ec9ef3cac8e220093d61a2f7a42f53c9cb22/PyTLDR-0.1.4.tar.gz
Requirement already satisfied: numpy>=1.8.0 in /anaconda3/lib/python3.6/site-packages (from PyTLDR) (1.14.5)
Requirement already satisfied: nltk>=3.0.0 in /anaconda3/lib/python3.6/site-packages (from PyTLDR) (3.2.5)
Requirement already satisfied: scipy>=0.13.2 in /anaconda3/lib/python3.6/site-packages (from PyTLDR) (1.0.0)
Requirement already satisfied: scikit-learn>=0.15.2 in /anaconda3/lib/python3.6/site-packages (from PyTLDR) (0.19.1)
Collecting goose-extractor>=1.0.25 (from PyTLDR)
  Using cached https://files.pythonhosted.org/packages/ab/f3/2e89688e4e1d8786e542ea460431f24f1392d885e60303dc20d476a96424/goose-extractor-1.0.25.tar.gz
Requirement already satisfied: networkx>=1.9.1 in /anaconda3/lib/python3.6/site-packages (from PyTLDR) (2.1)
Requirement already satisfied: six in /anaconda3/lib/python3.6/site-packages (from nltk>=3.0.0->PyTLDR) (1.10.0)
Requirement already satisfied: Pillow in /anaconda3/lib/python3.6/site-packages (from goose-extractor>=1.0.25->PyTLDR) (5.0.0)
Requirement already satisfied: lxml in /anaconda3/lib/python3.6/site-packages (from goose-extractor>=1.0.25->PyTLDR) (4.1.1)
Requirement already satisfied: cssselect in /anaconda3/lib/python3.6/site-packages (from goose-extractor>=1.0.25->PyTLDR) (1.0.3)
Collecting jieba (from goose-extractor>=1.0.25->PyTLDR)
  Using cached https://files.pythonhosted.org/packages/71/46/c6f9179f73b818d5827202ad1c4a94e371a29473b7f043b736b4dab6b8cd/jieba-0.39.zip
Collecting beautifulsoup (from goose-extractor>=1.0.25->PyTLDR)
  Using cached https://files.pythonhosted.org/packages/1e/ee/295988deca1a5a7accd783d0dfe14524867e31abb05b6c0eeceee49c759d/BeautifulSoup-3.2.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/vn/_v8bmt4j06xb2ngjcj01hzbc0000gn/T/pip-install-jsnnr7lf/beautifulsoup/setup.py", line 22
        print "Unit tests have failed!"
                                      ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print(int "Unit tests have failed!")?
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/vn/_v8bmt4j06xb2ngjcj01hzbc0000gn/T/pip-install-jsnnr7lf/beautifulsoup/

**Comment by ankitsharma1999** [comment]
This issue arises due to the version of python you are using. This module works with `python 2.x` not with `python 3.x`.

**Comment by AkshayVaghani** [comment]
thank you
